# Generated by Django 4.2.5 on 2023-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.IntegerField()),
                ('itemname', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('General LP', 'general_lp'), ('General UP', 'general_up'), ('General HS', 'general_hs'), ('General HSS', 'general_hss'), ('Arabic LP', 'arabic_lp'), ('Arabic UP', 'arabic_up'), ('Arabic HS', 'arabic_hs'), ('Sanskrit UP', 'sanskrit_up'), ('Sanskrit HS', 'sanskrit_hs')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='itempoints_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('General LP', 'general_lp'), ('General UP', 'general_up'), ('General HS', 'general_hs'), ('General HSS', 'general_hss'), ('Arabic LP', 'arabic_lp'), ('Arabic UP', 'arabic_up'), ('Arabic HS', 'arabic_hs'), ('Sanskrit UP', 'sanskrit_up'), ('Sanskrit HS', 'sanskrit_hs')], max_length=25)),
                ('item', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='kaloapp/static/item_points')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='login_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='school_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolcode', models.IntegerField()),
                ('schoolname', models.CharField(max_length=25)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='schoolpoints_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='kaloapp/static/school_points')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
