# Generated by Django 4.2.5 on 2023-10-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaloapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolpoint_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='kaloapp/static/school_points')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='schoolpoints_model',
        ),
    ]
