# Generated by Django 4.2.5 on 2023-10-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaloapp', '0002_schoolpoint_model_delete_schoolpoints_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_model',
            old_name='place',
            new_name='category',
        ),
        migrations.AddField(
            model_name='school_model',
            name='agrade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_model',
            name='bgrade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_model',
            name='cgrade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_model',
            name='mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school_model',
            name='schoolname',
            field=models.CharField(max_length=100),
        ),
    ]
