# Generated by Django 4.2.5 on 2023-10-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaloapp', '0003_rename_place_school_model_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_model',
            name='category',
            field=models.CharField(choices=[('General LP', 'general_lp'), ('General UP', 'general_up'), ('General HS', 'general_hs'), ('General HSS', 'general_hss'), ('Arabic LP', 'arabic_lp'), ('Arabic UP', 'arabic_up'), ('Arabic HS', 'arabic_hs'), ('Sanskrit UP', 'sanskrit_up'), ('Sanskrit HS', 'sanskrit_hs')], max_length=50),
        ),
    ]
