# Generated by Django 4.2.5 on 2023-10-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaloapp', '0004_alter_school_model_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_model',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
