# Generated by Django 4.2.5 on 2023-10-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaloapp', '0005_alter_school_model_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempoints_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schoolpoint_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
